Bug Fix - Coefficients of reactions
guillemborrell/thermopy pull request #2
Opened 2023-05-09 13:57 UTC by nof21

Fixed coefficient of reactions for the nasa9polynomials.py
Before was only read the reactants coefficients

2023-05-09 21:12 UTC, guillemborrell requested changes
Hi @nof21 and thanks for the patch! I've seen that the change also brings in other spurious files, like the thermopy.egg-info, and IDE-related files. Could you please remove them?

2023-05-10 07:44 UTC, nof21 reviewed
I have removed the unnecessary files.

2023-05-10 08:40 UTC, guillemborrell requested changes

2023-05-10 08:40 UTC, guillemborrell commented on thermopy/nasa9polynomials.py
> +    print('test')
Thanks! One last change request. Can you please remove this print statement too?

2023-09-28 11:08 UTC, guillemborrell reviewed
All good

2023-09-28 11:09 UTC, guillemborrell commented
@nof21 Sorry for coming back to this after a long time. Feel free to reopen the PR so I can merge.

2023-09-28 11:25 UTC, nof21 commented
Restored and reopened

2023-09-28 11:32 UTC, guillemborrell approved these changes
Thanks!

2023-09-28 11:32 UTC, merged